import React from 'react';
import { connect } from 'react-redux'
import { reduxForm } from 'redux-form';
import { makeValidator, errorTextFactory } from '../../../misc/formUtils'
import { dialogClose } from '../../core/ducks/dialog'
import TextField from 'material-ui/TextField';
import Button from '../../../components/Button'
import Dialog from '../../core/containers/Dialog';

export const formName = 'create-app';

const CreateAppDialog = (props) =>  {
  const {dialogName, dialogClose, fields: {name}, handleSubmit, submitting, submitFailed} = props;
  const errorText = errorTextFactory(submitFailed);

  const actions = [
    <Button label="Cancel"
      onTouchTap={() => dialogClose(dialogName)} />,
    <Button label="Create application" success raised disabled={submitting} icon="create"
      onTouchTap={handleSubmit} />
  ];

  return (
    <Dialog name={dialogName} title="Create application" actions={actions}>
      <p>Choose name for your new application (it can be changed later). The application will
      be based on the data generated by the selected pipeline.</p>
      <form onSubmit={handleSubmit} className={props.className}>
        <div>
          <TextField floatingLabelText="Name" {...name} {...errorText(name)} fullWidth />
        </div>
      </form>
    </Dialog>
  );
};

const validate = makeValidator({
  properties: {
    name: {
      allowEmpty: false,
      message: 'Please specify the name of the new application'
    }
  }
});

export default reduxForm({
  form: formName,
  fields: ['name'],
  validate
})(CreateAppDialog);
