import { createSelector } from 'reselect'

// Selectors (over the state generated by the router)

/** Extract route parameters injected by the router (works only for 'pages', i. e. route components) */
export const routeParamsSelector = (_, props) => props.params;

export const createRouteParamSelector = param =>
  createSelector([routeParamsSelector], params => params[param]);
